In [25]:
import sys
import numpy as np 
import matplotlib as plt

In [26]:
print(sys.version)
print(np.__version__)
print(plt.__version__)

3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
1.26.4
3.9.0


## making of a sigle neuron (rough work)

In [27]:
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2
result=bias+inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]
print(result)


2.3000000000000003


In [28]:
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2
result=bias+inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]
print(result)

4.800000000000001


## coding the layer (simple rough work)

In [29]:
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]

bias1=2
bias2=3
bias3=0.5

result=[bias1+inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3],
        bias2+inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3],
        bias3+inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]]

print(result)

[4.800000000000001, 1.21, 2.385]


# cleaning the rough work 

In [30]:
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

layer_output=[]
for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output=0
    for n_input,weight in zip(inputs,neuron_weights):
        neuron_output+=n_input*weight
    neuron_output+=neuron_bias
    layer_output.append(neuron_output)

print(layer_output)


[4.8, 1.21, 2.385]


## implementing the dot product using numpy

In [31]:
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
         
biases=[2,3,0.5]

layer1_outputs=np.dot(inputs,np.array(weights).T)+biases

print(layer1_outputs)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [32]:
weights2=[[0.1,-0.14,0.5],
         [-0.5,0.12,0.33],
         [-0.44,0.73,-0.13]]
         
biases2=[-1,2,-0.5]

layer2_outputs=np.dot(layer1_outputs,np.array(weights2).T)+biases2
print(layer2_outputs)

[[ 0.5031   0.53225 -2.03875]
 [ 0.2434  -2.6012  -5.7633 ]
 [-0.99314  1.4297  -0.35655]]


## Learning activation function from scratch 

In [33]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output= []

for i in inputs:
    output.append(max(0,i))


print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


## Building softmax activation functions 
# these are the functions used on the output layer for the classification

In [34]:
import math 

layer_output=[4.8,1.21,2.385] 
E=math.e

exp_values=[]
for output in layer_output:
    exp_values.append(E**output)

print(exp_values)

norm_base=sum(exp_values)
norm_values=[]

for norm in exp_values:
    norm_values.append(norm/norm_base)

print(norm_values)
print(sum(norm_values))



[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


## Removing the hard code

In [35]:
import numpy as np
layer_output=[[4.8,1.21,2.385],
              [8.9,-1.81,0.2],
              [1.41,1.051,0.026]]
exp_values=np.exp(layer_output)
print(exp_values)

print(np.sum(layer_output,axis=1,keepdims=True))
norm_values=exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(norm_values)



[[1.21510418e+02 3.35348465e+00 1.08590627e+01]
 [7.33197354e+03 1.63654137e-01 1.22140276e+00]
 [4.09595540e+00 2.86051020e+00 1.02634095e+00]]
[[8.395]
 [7.29 ]
 [2.487]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


## Calculating the loss function 

In [36]:
import math 

softmax_output=[0.7,0.1,0.2]
target_output=[1,0,0]


loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2])

print(loss)
loss=-math.log(softmax_output[0])
print(loss)
print(-math.log(0.7))
print(-math.log(0.5))


0.35667494393873245
0.35667494393873245
0.35667494393873245
0.6931471805599453


## cleaning up things

In [37]:
import numpy as np 

softmax_output=np.array([[0.7,0.1,0.2],
                         [0.1,0.5,0.4],
                         [0.02,0.9,0.88]])

class_targets=[0,1,1]
neg_loss=-np.log(softmax_output[range(len(softmax_output)),class_targets])

average_loss=np.mean(neg_loss)
print(average_loss)

0.38506088005216804
